# Generated by Django 3.1.7 on 2021-03-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210325_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbet',
            name='gain',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='result',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
