name: deploy

on: 
  push:
    branches:
      - develop

jobs:
  deliver-main:
    runs-on: ubuntu-latest
    env:
      path: ~/www/

    steps:
      #- name: stop server during deployment
        #run: sudo sv stop nginx

      - name: checkout main branch
        uses: actions/checkout@v2
        with:
          ref: develop
          #in case we want to deploy a certain branch (ex : serve main and develop at different points)
          
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
          
      - name: Capistrano deploy
        uses: miloserdow/capistrano-deploy@master
        with:
          target: production
          deploy_key: ${{ secrets.SERVER_PRIVATE }}
          #enc_rsa_key_val: ${{ secrets.DEPLOY_ENC_PRIVATE_KEY }}
          ssh-private-key: ${{ secrets.PRIV_KEY }}
